### ISSUE TITLE
Deprecation warning: Use of deprecated folder mapping "./"  in the "exports" field

### ISSUE THREAD

**Issue by fs-c** [postcss/postcss#1519]
I just got the following warning:

```
(node:14084) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./"
 in the "exports" field module resolution of the package at ...\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
```

It looks like the deprecated mapping is still in use on the most recent version. I haven't looked into it so I don't know if this is really as simple as exchanging `./` for `./*`, just thought I'd let you know.

**Comment by Semigradsky** [comment]
@fs-c what is your `node` version?

**Comment by fs-c** [comment]
I'm on Node version `v15.5.1`, npm version is `7.3.0`.

Sorry, should have mentioned this in the OP.

**Comment by Semigradsky** [comment]
@fs-c https://github.com/postcss/postcss/issues/1455#issuecomment-760690757

Friendly advice: updates often if you use unstable versions. Or just use [stable `14.x` (LTS)](https://nodejs.org/en/about/releases/).

**Comment by altro3** [comment]
@Semigradsky Hi! This warning also ocurred wiith nodejs 16.0 (current lts).

**Comment by deadcoder0904** [comment]
I think the PR should be simple.

Need to make this `./`:

https://github.com/postcss/postcss/blob/dc6cff1d7f9e0d6cba440d1b4f797a0f57b13595/package.json#L8-L13

And specify `node` v16 in the `engine`:

https://github.com/postcss/postcss/blob/dc6cff1d7f9e0d6cba440d1b4f797a0f57b13595/package.json#L5-L7

And make a release. Anything I'm missing?

**Comment by ai** [comment]
Fixed in the latest PostCSS release

**Comment by deadcoder0904** [comment]
Hey @ai, I still get the error even though I've updated to v8.2.12

**Comment by ai** [comment]
Show the full warning text

**Comment by deadcoder0904** [comment]
> (node:12493) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at ~/my-app/node_modules/next/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by ai** [comment]
@deadcoder0904 seems like you still using old PostCSS in Next.js dependencies.

Update nested dependencies with `npm update` or `yarn upgrade`.

**Comment by jaydenseric** [comment]
@deadcoder0904 Next.js very annoyingly pins their dependencies (not using `^`), so you have to wait for Next.js to manually publish their updated dependency versions to get the latest `postcss` patch. If you run `npm ls postcss`, you will see that you have two versions in `node_modules` because of Next.js pinning their dependencies.

It's annoyed me for years that they do that.

**Comment by karlhorky** [comment]
One option to avoid waiting for a package to upgrade a pinned dependency is to use [Yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/):

**`package.json`**

```json
{
  "resolutions": {
    "postcss": "8.2.12"
  }
}
```

But probably not such a big deal for a deprecation warning...

**Comment by deadcoder0904** [comment]
@jaydenseric that makes sense. I already did `npm list` & saw that I indeed installed `postcss` correctly.

@karlhorky it's not a big of a deal to me tbh.

**Comment by LeparaLaMapara** [comment]
Hi I tried the above mentioned solution, I still get the same error, here are my npm list:

├── @testing-library/jest-dom@5.11.6
├── @testing-library/react@11.2.2
├── @testing-library/user-event@12.6.0
├── axios@0.21.1
├── bootstrap@4.5.3
├── gh-pages@3.2.3
├── postcss-loader@3.0.0
├── postcss@7.0.35
├── react-bootstrap@1.4.0
├── react-dom@17.0.1
├── react-github-calendar@2.0.2
├── react-icons@4.2.0
├── react-parallax-tilt@1.4.68
├── react-particles-js@3.4.1
├── react-router-dom@5.2.0
├── react-scripts@4.0.1
├── react@17.0.1
├── typewriter-effect@2.17.0
└── web-vitals@0.2.4

**Comment by vitoneto** [comment]
I fixed it changing de node version.

It was on v16 and i just changed to v14 with 'nvm use 14'.

**Comment by matheusPinheiroP** [comment]
> @jaydenseric that makes sense. I already did `npm list` & saw that I indeed installed `postcss` correctly.
> 
> @karlhorky it's not a big of a deal to me tbh.

It's not working for me
