### ISSUE TITLE
DeprecationWarning under Node.js 16.0.0

### ISSUE THREAD

**Issue by adp-psych** [postcss/postcss#1561]
```
(node:301479) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at PROJECT_ROOT/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
```

**Comment by ai** [comment]
What OS do you have?

In Node.js 15 it was a Windows error.

**Comment by doberkofler** [comment]
@ai Same here on macOS  11.2.3 after just upgrading to nodejs v16.0.0.

**Comment by alexander-akait** [comment]
Here problems https://github.com/postcss/postcss/blob/main/package.json#L14, need change to `"./*": "./*.js"`, but it breaks old Node.js compatibility (because not all version supported `*`), to be honestly Node.js do not recommended use it in past...

**Comment by ai** [comment]
I created an issue in Node.js to disable warning or suggest the solution https://github.com/nodejs/node/issues/38353

**Comment by ai** [comment]
OK, I specified all dirs manually in `package.exports` https://github.com/postcss/postcss/commit/96faacb974dcc5c3ff17c97e16785abcbea410d2

**Comment by alexander-akait** [comment]
Yep, good solution

**Comment by czue** [comment]
I tried upgrading and am now getting:
```
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /node_modules/postcss/package.json
```

**Comment by ai** [comment]
@czue fixed in https://github.com/postcss/postcss/commit/8e6088f99ca8ae92f70d5207a8478cd22e6ec420 and released in 8.2.12.

**Comment by czue** [comment]
confirmed fixed, thanks for the prompt response!

**Comment by yigithanyucedag** [comment]
I'm still facing the issue
postcss version 8.2.14
node version v16.1.0
