### ISSUE TITLE
Change to nanocolors breaks build pipelines with nonstanard file extension

### ISSUE THREAD

**Issue by kdnutrien** [postcss/postcss#1639]
```
While trying to resolve module `nanocolors` from file `my-project/node_modules/sanitize-html/node_modules/postcss/lib/css-syntax-error.js`, 
the package `my-project/node_modules/sanitize-html/node_modules/nanocolors/package.json` was successfully found. 
However, this package itself specifies a `main` module field that could not be resolved (`/my-project/node_modules/sanitize-html/node_modules/nanocolors/index.browser.cjs`. Indeed, none of these files exist:

  * /my-project/node_modules/sanitize-html/node_modules/nanocolors/index.browser.cjs(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * /my-project/node_modules/sanitize-html/node_modules/nanocolors/index.browser.cjs/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
```

**Comment by kdnutrien** [comment]
@ai looks like you know about this one - https://github.com/facebook/metro/issues/535

**Comment by ai** [comment]
I released `nanocolors 0.2.12`. Can you check the issue there?

**Comment by ai** [comment]
@kdnutrien did this fix helped?

**Comment by kdnutrien** [comment]
Looking at my lockfile, I'm still getting nanocolors 0.1.12 from browserslist 4.17.1

Will try to force resolution to 0.2.12 with `resolutions` and see if that does it.

**Comment by ai** [comment]
@kdnutrien I also released Browserslist 4.17.2 with `nanocolors ^0.2.0`

**Comment by kdnutrien** [comment]
Thanks, yes I believe so.  Forcing yarn resolutions did it for me.
